/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Usuario
 */
public class FrmClientes extends javax.swing.JFrame {

    /**
     * Creates new form FrmClientes
     */
    public FrmClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtEmail = new javax.swing.JTextPane();
        lblEmail = new javax.swing.JLabel();
        lblTlfTrabajo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTrabajo = new javax.swing.JTextPane();
        lblFechCredito = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtFechCredit = new javax.swing.JTextPane();
        lblValorCredito = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtValorCredito = new javax.swing.JTextPane();
        lblTlfresidencia = new javax.swing.JLabel();
        lblNumFactura = new javax.swing.JLabel();
        lblTipoCartera = new javax.swing.JLabel();
        lblNumCuotas = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtResidencia = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtNumFactura = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtTipoCartera = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtNumCuotas = new javax.swing.JTextPane();
        lblCedula = new javax.swing.JLabel();
        txtResidencial = new javax.swing.JTextField();
        lblExpedicion = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtDepartamento = new javax.swing.JTextField();
        lblProfesion = new javax.swing.JLabel();
        lblResidencial = new javax.swing.JLabel();
        lblCiudad = new javax.swing.JLabel();
        lblDepartamento = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtExpedicion = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtProfesion = new javax.swing.JTextField();
        cmdAlta = new javax.swing.JButton();
        cmdEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(txtEmail);

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmail.setText("E-Mail:");

        lblTlfTrabajo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTlfTrabajo.setText("Tel. Trabajo:");

        jScrollPane2.setViewportView(txtTrabajo);

        lblFechCredito.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFechCredito.setText("Fecha de Credito:");

        jScrollPane3.setViewportView(txtFechCredit);

        lblValorCredito.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblValorCredito.setText("Valor Credito:");

        jScrollPane4.setViewportView(txtValorCredito);

        lblTlfresidencia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTlfresidencia.setText("Tel. Residencia:");

        lblNumFactura.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNumFactura.setText("Num. Factura:");

        lblTipoCartera.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTipoCartera.setText("Tipo Cartera:");

        lblNumCuotas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNumCuotas.setText("Num. Cuotas:");

        jScrollPane5.setViewportView(txtResidencia);

        jScrollPane6.setViewportView(txtNumFactura);

        jScrollPane7.setViewportView(txtTipoCartera);

        jScrollPane8.setViewportView(txtNumCuotas);

        lblCedula.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCedula.setText("Cédula : ");

        txtResidencial.setText(" ");

        lblExpedicion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblExpedicion.setText("Lugar de Expedición : ");

        txtCiudad.setText(" ");

        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombre.setText("Nombre Completo : ");

        txtDepartamento.setText(" ");

        lblProfesion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblProfesion.setText("Profesión : ");

        lblResidencial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblResidencial.setText("Dirección Residencial :");

        lblCiudad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCiudad.setText("Ciudad : ");

        lblDepartamento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDepartamento.setText("Departamento : ");

        txtCedula.setText(" ");

        txtExpedicion.setText(" ");

        txtNombre.setText(" ");

        txtProfesion.setText(" ");

        cmdAlta.setText("Alta");

        cmdEliminar.setText("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombre)
                    .addComponent(lblCedula))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(txtNombre))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblExpedicion)
                    .addComponent(lblProfesion)
                    .addComponent(lblCiudad)
                    .addComponent(lblTlfTrabajo)
                    .addComponent(lblFechCredito)
                    .addComponent(lblValorCredito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(txtExpedicion, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProfesion, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(txtCiudad)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane8))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblResidencial)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDepartamento)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTlfresidencia)
                                    .addComponent(lblNumFactura)
                                    .addComponent(lblTipoCartera))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtResidencial, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(txtDepartamento)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane6)
                            .addComponent(jScrollPane7))
                        .addGap(112, 112, 112)
                        .addComponent(lblEmail))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(lblNumCuotas)
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)))
                .addGap(267, 267, 267))
            .addGroup(layout.createSequentialGroup()
                .addGap(399, 399, 399)
                .addComponent(cmdAlta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdEliminar)
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCedula)
                                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblExpedicion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtExpedicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addComponent(lblNombre))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblProfesion)
                                .addComponent(txtProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblResidencial)
                            .addComponent(txtResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCiudad)
                            .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDepartamento)
                                .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblEmail))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTlfresidencia)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTlfTrabajo)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNumFactura)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechCredito)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTipoCartera)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValorCredito)))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNumCuotas)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdAlta)
                    .addComponent(cmdEliminar))
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cmdAlta;
    public javax.swing.JButton cmdEliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JLabel lblCedula;
    public javax.swing.JLabel lblCiudad;
    public javax.swing.JLabel lblDepartamento;
    public javax.swing.JLabel lblEmail;
    public javax.swing.JLabel lblExpedicion;
    public javax.swing.JLabel lblFechCredito;
    public javax.swing.JLabel lblNombre;
    public javax.swing.JLabel lblNumCuotas;
    public javax.swing.JLabel lblNumFactura;
    public javax.swing.JLabel lblProfesion;
    public javax.swing.JLabel lblResidencial;
    public javax.swing.JLabel lblTipoCartera;
    public javax.swing.JLabel lblTlfTrabajo;
    public javax.swing.JLabel lblTlfresidencia;
    public javax.swing.JLabel lblValorCredito;
    public javax.swing.JTextField txtCedula;
    public javax.swing.JTextField txtCiudad;
    public javax.swing.JTextField txtDepartamento;
    public javax.swing.JTextPane txtEmail;
    public javax.swing.JTextField txtExpedicion;
    public javax.swing.JTextPane txtFechCredit;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextPane txtNumCuotas;
    public javax.swing.JTextPane txtNumFactura;
    public javax.swing.JTextField txtProfesion;
    public javax.swing.JTextPane txtResidencia;
    public javax.swing.JTextField txtResidencial;
    public javax.swing.JTextPane txtTipoCartera;
    public javax.swing.JTextPane txtTrabajo;
    public javax.swing.JTextPane txtValorCredito;
    // End of variables declaration//GEN-END:variables
}
